# https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544
# This workflow doesn't have access to secrets and has a read-only token
# It will trigger `cicd`, which has permissions
name: Push Trigger
on:
  push:
    branches: [ main, develop ]

jobs:
  flag:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Push triggered"
